development: &default
  adapter: postgresql
  database: vizamyl_development
  encoding: utf8
  host: localhost
  password: 'password'
  min_messages: warning
  pool: 2
  timeout: 5000
  user: <%= ENV['USER'] %>

test:
  <<: *default
  database: vizamyl_test

staging:
  <<: *default

production:
  <<: *default
