# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
invite_codes: &invite_codes
  # New Codes
  # 'VIZRTHCP':
  #   type: 'default'
  # 'VIZRTCASES': 
  #   type: 'fast_forward'
  # 'VIZRTSUPERU':
  #   type: 'in_person'

  # Old Codes
  
  # Japanese default
  'UX7WZ':
    type: 'default'


  # US default
  '8Q5MH':
    type: 'default'

  # Rest Codes
  '8ONEC':
    type: 'default'
  '593X1':
    type: 'in_person'
  'striatum-en':
    type: 'in_person'
  '3NX3H':
    type: 'fast_forward'
  'injection-en':
    type: 'fast_forward'
  'XAYOT':
    type: 'default'
  'DGXWA':
    type: 'in_person'
  'striatum-en-gb':
    type: 'in_person'
  'APNZ5':
    type: 'fast_forward'
  'injection-en-gb':
    type: 'fast_forward'
  # '8Q5MH':
  #   type: 'default'
  'TIEZM':
    type: 'in_person'
  'KN67H':
    type: 'fast_forward'
  '2EGKW':
    type: 'default'
  'OJBHO':
    type: 'in_person'
  'striatum-de':
    type: 'in_person'
  '1LG9X':
    type: 'fast_forward'
  'injection-de':
    type: 'fast_forward'
  'IFDUA':
    type: 'default'
  'IQSY9':
    type: 'in_person'
  'striatum-de-at':
    type: 'in_person'
  'DIMKF':
    type: 'fast_forward'
  'injection-de-at':
    type: 'fast_forward'
  'OB1ZO':
    type: 'default'
  'IFXJ8':
    type: 'in_person'
  'striatum-fr':
    type: 'in_person'
  'SMCT5':
    type: 'fast_forward'
  'injection-fr':
    type: 'fast_forward'
  'IYQQO':
    type: 'default'
  'Q594R':
    type: 'in_person'
  'striatum-it':
    type: 'in_person'
  '8XNGO':
    type: 'fast_forward'
  'injection-it':
    type: 'fast_forward'
  'QYIE4':
    type: 'default'
  'ZBQXH':
    type: 'in_person'
  'striatum-es':
    type: 'in_person'
  '89RFQ':
    type: 'fast_forward'
  'injection-es':
    type: 'fast_forward'
  'vzmylinvite349':
    type: 'default'
  'ausvzmylinvite':
    type: 'default'
  'amyloid':
    type: 'default'
  'emission':
    type: 'default'
  'positron':
    type: 'default'
  'resonance':
    type: 'default'
  'sagittal':
    type: 'default'
  'plaque':
    type: 'default'
  'tomography':
    type: 'default'
  '3AO9Z':
    type: 'default'
  '6NGUI':
    type: 'fast_forward'
  'TLX87':
    type: 'in_person'
  'XMQNQ':
    type: 'default'
  '14Z8W':
    type: 'fast_forward'
  'BYJPN':
    type: 'in_person'
  'JE5H7':
    type: 'default'
  'Y1BQG':
    type: 'fast_forward'
  'W1XZA':
    type: 'in_person'
  'PQ1BK':
    type: 'default'
  'APZK8':
    type: 'fast_forward'
  'FETAN':
    type: 'in_person'
  'KRVUK':
    type: 'default'
  'IXLTV':
    type: 'fast_forward'
  'XME7M':
    type: 'in_person'
  '6SQO7':
    type: 'default'
  'D5Z4I':
    type: 'fast_forward'
  'N7NPH':
    type: 'in_person'
  'G63RW':
    type: 'default'
  'HARG9':
    type: 'fast_forward'
  'IN3X3':
    type: 'in_person'
  'SK6AO':
    type: 'default'
  'BJCPJ':
    type: 'fast_forward'
  'KCB6G':
    type: 'in_person'
  'OP1U7':
    type: 'default'
  '2Y8W7':
    type: 'fast_forward'
  'BJHCU':
    type: 'in_person'
  'LV7MD':
    type: 'default'
  'GY6B1':
    type: 'fast_forward'
  'WT6YQ':
    type: 'in_person'
  '9Q1PE':
    type: 'default'
  'KT8PL':
    type: 'fast_forward'
  '6DZQT':
    type: 'in_person'
  'TXO8X':
    type: 'default'
  'VLAEN':
    type: 'fast_forward'
  '8P32U':
    type: 'in_person'
  '6LRA0':
    type: 'default'
  'ZIDZZ':
    type: 'fast_forward'
  'MW04Z':
    type: 'in_person'
  'RN4GD':
    type: 'default'
  '8DA84':
    type: 'fast_forward'
  'QTBVA':
    type: 'in_person'
  '4NYFN':
    type: 'default'
  'JVMEU':
    type: 'fast_forward'
  'MFTOT':
    type: 'in_person'
  '8OWF6':
    type: 'default'
  'M2TIS':
    type: 'fast_forward'
  'BOB12':
    type: 'in_person'
  'QR3HK':
    type: 'default'
  'AM5WR':
    type: 'in_person'
  'HP9WT':
    type: 'fast_forward'
  'KQITH':
    type: 'default'
  'RCVTS':
    type: 'in_person'
  'MZNXQ':
    type: 'fast_forward'
  'SWTRR':
    type: 'default'
  'HVLMA':
    type: 'in_person'
  'LH4QZ':
    type: 'fast_forward'
  'WB5PE':
    type: 'default'
  'CHQYQ':
    type: 'in_person'
  'BNA3E':
    type: 'fast_forward'
  # 'UX7WZ':
  #   type: 'default'
  '2PNWU':
    type: 'in_person'
  'ST66N':
    type: 'fast_forward'
  'LL0RD':
    type: 'default'
  'P2ROF':
    type: 'fast_forward'
  'T1DOP':
    type: 'in_person'
  'BRGD4':
    type: 'default'
  'T8D48':
    type: 'fast_forward'
  'TWVBA':
    type: 'in_person'

test: &test
  secret_key_base: d38e5e398cf6c52255e2b370d89eff7129fcce95f9c6140016e4db3ec98f0054197b464b6edba50943dfbba26a73d5c6698749b43a82e0b828172a1f2275ea94

development: &development
  secret_key_base: 4b746f750ff54b449337e06bdb76637c0e5a0c8141385904a551a6ab5791164d6abe34e516bf8f6c1d10c38cac754bf568d1ac2a9297e6995565a7aa8dbc6efd
  asset_host: 'dxugyqzjahy7a.cloudfront.net'
  content_host: 'dki1hrtf104z9.cloudfront.net'
  google_analytics_key: 'UA-56326872-1'
  invite_codes:
    <<: *invite_codes

staging: &staging
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  asset_host: 'dxugyqzjahy7a.cloudfront.net'
  content_host: 'dki1hrtf104z9.cloudfront.net'
  google_analytics_key: 'UA-56326872-1'
  invite_codes:
    <<: *invite_codes

sandbox:
  <<: *staging
  asset_host: 'vizamyl-sandbox.herokuapp.com'
  invite_codes:
    <<: *invite_codes

production: &production
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  # asset_host: 'assets.readvizamyl.com' # Disabled as GE refused wildcart cert which broke this
  # asset_host: 'd3tnwc4szodljd.cloudfront.net' # Disabled, as cloudfront is not working
  asset_host: 'www.readvizamyl.com' # Serve CSS from Heroku via rails_serve_static_assets
  # content_host: 'content.readvizamyl.com' # Disabled as GE refused wildcart cert which broke this
  content_host: 'djqy74tsvke0j.cloudfront.net' # Serve videos from S3 via cloudfront
  google_analytics_key: 'UA-56326872-2'
  invite_codes:
    <<: *invite_codes
